Finish overhaul of `lb`
Some highlights:

  * Now a variable `HTAccess` to save repetition.

  * Declared `MaxNum` as an integer, to keep it local.

  * Added back `chosen`, since it's required several times later.

  * Fixed incorrect indices in array variables. Please test.

  * Overhauled `delete()`, cleaning and optimizing it.

  * Writing HTML code to files is no longer code-vomit. Please test.

  * Where possible, preferred `printf` built-in, over `date`.

  * Function `confirm()` now tidier and its logic sane.

  * Function `delete()` usage of `rm` has been slightly tweaked.

  * Function `revise()` now has cleaner formatting.

  * Final case statement has been cleaned up and logic reviewed.

  * Overhauled the user `--help` style output; it's now much cleaner.

  * Addressed various syntactical redundancies throughout.

You'll want to check the program works as you like _before_ accepting.
I have to say, now that it's in much better shape, it's quite a nifty
shell program.

Be sure to update the usage output mentioned above with your own
description, unless you like the one I gave it, and the full name for
`lb`, rather than just the abbreviation; just makes it less ambiguous.

All of these work has taken a few hours, so I hope it all helps. :)

diff --git a/lb b/lb
--- a/lb
+++ b/lb
@@ -6,6 +6,7 @@ css="../style.css"
 blogfile="2019.html"
 indexfile="blogindex.html"
 rssfile="rss.xml"
+HTAccess="$webdir/blog/.htaccess"
 [ -z "$EDITOR" ] && EDITOR="vim"
 
 FAIL(){
@@ -27,7 +28,7 @@ if [ ! -d "$webdir/blog/.drafts" ]; then
 				FAIL 1 $LINENO "Write access required for directory creation."
 			fi
 
-			echo "Options +Indexes" > "$webdir/blog/.htaccess" ;;
+			echo "Options +Indexes" > "$HTAccess" ;;
 		*)
 			exit ;;
 	esac
@@ -48,7 +49,6 @@ newpost() {
 			' <<< "$(iconv -cf UTF-8 -t ASCII//TRANSLIT <<< "$title")"
 		}
 
-		local HTAccess="$webdir/blog/.htaccess"
 		if [ -f "$HTAccess" ] && [ -r "$HTAccess" ]; then
 			printf "AddDescription \"%s\" \"%s.html\"\n" "$title" "$(url)" >> "$HTAccess"
 		else
@@ -71,7 +71,7 @@ newpost() {
 
 listandReturn() {
 	readarray ListArr <<< "$(ls -rc1 "$1")"
-	MaxNum=$[${#ListArr[@]} + 1]
+	declare -i MaxNum=$[${#ListArr[@]} + 1]
 
 	printf "Listing contents of '%s'...\n" "$1"
 	declare -i Count=0
@@ -82,7 +82,8 @@ listandReturn() {
 
 	read -ep "Pick an entry to '$2', or 'Ctrl-C' to cancel: "
 	if [[ $REPLY =~ ^[0-9]+$ ]]; then
-		basefile=${ListArr[REPLY]##*/}
+		chosen=${ListArr[REPLY - 1]}
+		basefile=${ListArr[REPLY - 1]##*/}
 		base=${basefile%.*}
 	elif [ "$REPLY" -lt 1 -o "$REPLY" -gt $MaxNum ]; then
 		FAIL 1 $LINENO "Invalid response -- out of range."
@@ -90,47 +91,164 @@ listandReturn() {
 		FAIL 1 $LINENO "Invalid response -- integer (1-$MaxNum) required."
 	fi
 
-	unset Iter ListArr MaxNum
+	unset Iter ListArr
 }
 
-publish() { \
+publish() {
 	delete
-	htaccessentry=$(grep "$basefile" "$webdir/blog/.htaccess")
-	realname="$(echo "$htaccessentry" | cut -d'"' -f2)"
-	rssdate="$(grep "$basefile" blog/.htaccess | sed "s/.*\.html\"* *#*//g" | tr -d '\n')"
-	[ -z "$rssdate" ] && rssdate="$(LC_TIME=en_US date '+%a, %d %b %Y %H:%M:%S %z')" # RSS date formats must comply with standards to validate.
-	webdate="$(date '+%a, %d %b %Y %H:%M:%S %z')" # But this visible date you can set to any format.
+
+	realname=$(awk -F '"' -v B="$basefile" '/$basefile/{print($2)}' "$HTAccess")
+	rssdate=$(grep "$basefile" blog/.htaccess | sed "s/.*\.html\"* *#*//g" | tr -d '\n')
+
+	if [ -z "$rssdate" ]; then
+		# RSS date formats must comply with standards to validate.
+		rssdate=$(LC_TIME=en_US date '+%a, %d %b %Y %H:%M:%S %z')
+	fi
+
+	# But this visible date you can set to any format.
+	printf -v webdate '%(%a, %d %b %Y %H:%M:%S %z)T'
+
 	tmpdir=$(mktemp -d)
-	printf "<html>\\n<head>\\n<title>%s</title>\\n<link rel='stylesheet' type='text/css' href='%s'>\\n<meta charset='utf-8'/>\\n</head>\\n<body>\\n<h1>%s</h1>\\n<small>[<a href='%s#%s'>link</a>&mdash;<a href='%s'>standalone</a>]</small>\\n%s\\n<footer>by <strong><a href='%s'>%s</a></strong></footer>\\n</body>\\n\\n</html>" "$realname" "$css" "$realname" "../$blogfile" "$base" "$basefile" "$(cat "$webdir/blog/.drafts/$basefile")" "$website" "$name" > "$webdir/blog/$basefile"
-	printf "\\n<item>\\n<title>%s</title>\\n<guid>%s%s#%s</guid>\\n<pubDate>%s</pubDate>\\n<description><![CDATA[\\n%s\\n]]></description>\\n</item>\\n\\n" "$realname" "$website" "$blogfile" "$base" "$rssdate" "$(cat "$webdir/blog/.drafts/$basefile")" >  "$tmpdir/rss"
-	printf "<div class='entry'>\\n<h2 id='%s'>%s</h2>\\n<small>[<a href='#%s'>link</a>&mdash;<a href='%s'>standalone</a>]</small>\\n%s\\n<small>%s</small>\\n</div>\\n" "$base" "$realname" "$base" "blog/$basefile" "$(cat "$webdir/blog/.drafts/$basefile")" "$webdate" > "$tmpdir/html"
-	printf "<li>%s &ndash; <a href=\"blog/%s\">%s</a></li>\\n" "$(date '+%Y %b %d')" "$basefile" "$realname" > "$tmpdir/index"
+
+	> "$webdir/blog/$basefile"
+	while read; do
+		printf "%s\n" "$REPLY" >> "$webdir/blog/$basefile"
+	done <<-EOF
+		<html>
+
+		<head>
+		<title>$realname</title>
+		<link rel='stylesheet' type='text/css' href='$css'>
+		<meta charset='utf-8'/>
+		</head>
+		<body>
+		<h1>$realname</h1>
+		<small>[<a href='../$blogfile#$base'>link</a>&mdash;<a href='$basefile'>standalone</a>]</small>
+		$(< "$webdir/blog/.drafts/$basefile")
+		<footer>by <strong><a href='$website'></a>$name</strong></footer>
+		</body>
+
+		</html>
+	EOF
+
+	> "$tmpdir/rss"
+	while read; do
+		printf "%s\n" "$REPLY" >> "$tmpdir/rss"
+	done <<-EOF
+
+		<item>
+		<title>$realname</title>
+		<guid>$website$blogfile#$base</guid>
+		<pubDate>$rssdate</pubDate>
+		<description><![CDATA[
+		$(< "$webdir/blog/.drafts/$basefile")
+		]]></description>
+		</item>
+
+	EOF
+
+	> "$tmpdir/html"
+	while read; do
+		printf "%s\n" "$REPLY" >> "$tmpdir/html"
+	done <<-EOF
+		<div class='entry'>
+		<h2 id='$base'>$realname</h2>
+		<small>[<a href='#$base'>link</a>&mdash;<a href='blog/$basefile'>standalone</a>]</small>
+		$(< "$webdir/blog/.drafts/$basefile")
+		<small>$webdate</small>
+		</div>
+
+	EOF
+
 	sed -i "/<!-- LB -->/r $tmpdir/html" "$blogfile"
 	sed -i "/<!-- LB -->/r $tmpdir/rss" "$rssfile"
 	sed -i "/<!-- LB -->/r $tmpdir/index" "$indexfile"
-	sed -i "/ \"$base.html\"/d" "$webdir/blog/.htaccess"
-	echo "AddDescription \"$realname\" \"$basefile\" #$rssdate" >> "$webdir/blog/.htaccess"
+	sed -i "/ \"$base.html\"/d" "$HTAccess"
+
+	printf "<li>%(%Y %b %d)T &ndash; <a href=\"blog/%s\">%s</a></li>\n" -1 "$basefile" "$realname" > "$tmpdir/index"
+	printf "AddDescription \"%s\" \"%s\" #%s\n" "$realname" "$basefile" "$rssdate" >> "$HTAccess"
+
 	rm -f "$webdir/blog/.drafts/$chosen"
 }
 
-confirm() { read -erp "Really $1 \"$base\"? (y/N) " choice && echo "$choice" | grep -i "^y$" >/dev/null || exit 1 ;}
+confirm() {
+	read -ep "Really $1 \"$base\"? (y/N) "
+	case $REPLY in
+		[yY]) return 0 ;;
+		   *) return 1 ;;
+	esac
+}
 
-delete() { \
-	sed -i "/<item/{:a;N;/<\\/item>/!ba};/#$base<\\/guid/d" $rssfile
-	sed -i "/<div class='entry'>/{:a;N;/<\\/div>/!ba};/id='$base'/d" $blogfile
-	sed -i "/<li>.*<a href=\"blog\\/$base.html\">/d" $indexfile
-	rm "$webdir/blog/$basefile" 2>/dev/null && printf "Old blog entry removed.\\n" ;}
+delete() {
+	sed -i "/<item/{:a;N;/<\\/item>/!ba};/#$base<\\/guid/d" "$rssfile"
+	sed -i "/<div class='entry'>/{:a;N;/<\\/div>/!ba};/id='$base'/d" "$blogfile"
+	sed -i "/<li>.*<a href=\"blog\\/$base.html\">/d" "$indexfile"
 
-revise() { awk '/^<small>\[/{flag=1;next}/<footer>/{flag=0}flag' "$webdir/blog/$chosen" > "$webdir/blog/.drafts/$basefile"
+	if rm "$webdir/blog/$basefile" 2>/dev/null; then
+		printf "Old blog entry successfully removed.\n"
+	else
+		FAIL 0 $LINENO "Old blog entry failed to be removed."
+	fi
+}
+
+revise() {
+	awk '
+		/^<small>\[/{flag=1;next}/<footer>/{flag=0}flag
+	' "$webdir/blog/$chosen" > "$webdir/blog/.drafts/$basefile"
+
 	"$EDITOR" "$webdir/blog/.drafts/$basefile"
-	printf "Revision stored in blog/.drafts. Publish as normal entry when desired.\\n" ;}
+	printf "Revision stored in 'blog/.drafts' -- publish as normal entry when desired.\n"
+}
 
 case "$1" in
-	n*) newpost ;;
-	e*) listandReturn "$webdir"/blog/.drafts/ edit && "$EDITOR" "$webdir/blog/.drafts/$chosen" ;;
-	p*) listandReturn "$webdir"/blog/.drafts/ publish && publish ;;
-	t*) listandReturn "$webdir"/blog/.drafts/ trash && confirm trash && rm -f "$webdir/blog/.drafts/$chosen" && sed -i "/ \"$base.html\"/d" "$webdir/blog/.htaccess" ; printf "Draft deleted.\\n" ;;
-	d*) listandReturn "$webdir"/blog/ delete && confirm delete && delete && sed -i "/ \"$base.html\"/d" "$webdir/blog/.htaccess" ;;
-	r*) listandReturn "$webdir"/blog/ revise && revise ;;
-	*) printf "lb blog system by Luke Smith <luke@lukesmith.xyz>\\nUsage:\\n  lb n:\\tnew draft\\n  lb e:\\tedit draft\\n  lb p:\\tpublish/finalize draft\\n  lb r:\\trevise published entry\\n  lb t:\\tdiscard draft\\n  lb d:\\tdelete published entry\\n\\nBe sure to have the following pattern added to your RSS feed, blog file and blog index:\\n\\n<!-- LB -->\\n\\nNew content will be added directly below that sequence. This is required.\\nSee https://github.com/LukeSmithxyz/lb for more.\\n" ;;
+	n*)
+		newpost ;;
+	e*)
+		listandReturn "$webdir/blog/.drafts/" edit
+		$EDITOR "$webdir/blog/.drafts/$chosen" ;;
+	p*)
+		listandReturn "$webdir/blog/.drafts/" publish
+		publish ;;
+	t*)
+		listandReturn "$webdir/blog/.drafts/" trash
+		confirm trash && rm -f "$webdir/blog/.drafts/$chosen" || exit 1
+		sed -i "/ \"$base.html\"/d" "$HTAccess"
+		printf "Draft deleted.\n" ;;
+	d*)
+		listandReturn "$webdir"/blog/ delete
+		confirm delete && delete || exit 1
+		sed -i "/ \"$base.html\"/d" "$HTAccess" ;;
+	r*)
+		listandReturn "$webdir"/blog/ revise
+		revise ;;
+	*)
+		while read; do
+			printf "%s\n" "$REPLY"
+		done <<-EOF
+			            LB - Full Program Name Here (Version?)
+			            Written by Luke Smith <luke@lukesmith.xyz>
+
+			            Simple blog management system for your terminal.
+
+			SYNTAX:     lb [OPT]
+
+			OPTS:       new|n                   - Begin a new draft.
+			            edit|e                  - Edit an existing draft.
+			            publish|p               - Publish or finalize a draft.
+			            revise|r                - Revise a published entry.
+			            discard|t               - Discard an existing draft.
+			            delete|d                - Delete a published entry.
+
+			NOTE:       Be sure to have the following pattern added to your RSS
+			            feed, blog file and blog index:
+
+			              <!-- LB -->
+
+			            New content will be added directly below that sequence. This
+			            is required.
+
+			SITE:       https://github.com/LukeSmithxyz/lb
+		EOF
+
+		;;
 esac
