Optimize and clean up `newpost()` and initials
I'll be frank, I found the code difficult to read due to how convoluted
it was by its excessive compaction, akin to a wall-of-text. Not nice to
work with and not nice to view.

While having condensed code can be great, I believe you've taken it
too far. There is very little adherence to the traditional formatting
styles of the blocks, so I've sorted that for the initial stuff and for
the `newpost()` function. It's now a lot easier to read and edit.

I've added `FAIL()` (my error message system I use a lot) for cleaner
code and easier additional error messages. The syntax is:

```
FAIL [0|1] [$LINENO] [MESSAGE]
```

Where `0` would be to _not_ exit, and `1` would be to `exit 1`.

Your initial `read` (`ask`) now needs just the one character of input
before continuing (no need to press Enter), and the following case
statement now catches both upper- and lower-case of the 'Y' letter.

I've addressed the repeated use of the logical _and_ operator (`&&`), -
so that things are clearly defined.

You've used `-r` a lot with `read`, yet I see no reason why you would
want the expansion of escape sequences. Unless I've missed something, -
I went ahead and removed the flag.

I've greatly optimized how the `title` is parsed, using just `awk`, -
instead of a multitude of different processes.

I've cleaned up some variables, but that's nothing major.

If there are any bugs, please let me know so that I can fix them, as
with all commits to come.

Awesome idea for a script, by the way!

diff --git a/lb b/lb
--- a/lb
+++ b/lb
@@ -8,30 +8,74 @@ indexfile="blogindex.html"
 rssfile="rss.xml"
 [ -z "$EDITOR" ] && EDITOR="vim"
 
-[ ! -d "$webdir/blog/.drafts" ] &&
-read -erp "Initialize blog in $webdir?" ask &&
-	if [ "$ask" = "y" ]; then
-	printf "Initializing blog system...\\n"
-	mkdir -pv "$webdir/blog/.drafts" || printf "Error. Do you have write permissions in this directory?\\n"
-	echo "Options +Indexes" > "$webdir/blog/.htaccess"
-else
-	exit
+FAIL(){
+	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
+	[ $1 -eq 1 ] && exit 1
+}
+
+if [ ! -d "$webdir/blog/.drafts" ]; then
+	read -e -n 1 -p "Initialize blog in $webdir?" ask
+
+	case $ask in
+		[Yy])
+			printf "Initializing blog system...\\n"
+
+			Drafts="$webdir/blog/.drafts"
+			if [ -w "${Drafts%/*}" ]; then
+				mkdir -pv "$webdir/blog/.drafts"; then
+			else
+				FAIL 1 $LINENO "Write access required for directory creation."
+			fi
+
+			echo "Options +Indexes" > "$webdir/blog/.htaccess" ;;
+		*)
+			exit ;;
+	esac
 fi
 
-newpost() { read -erp "Give a title for your post:
-	" title
-	echo "$title" | grep "\"" >/dev/null && printf "Double quotation marks (\") are not allowed in entry titles.\\n" && exit
-	url="$(echo "$title" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
-	echo "AddDescription \"$title\" \"$url.html\"" >> "$webdir/blog/.htaccess" || { echo "Error: Is htaccess writeable?"; exit; }
-	[ -f "$webdir/blog/.drafts/$url.html" ] && echo "There is already an existing draft entry of that same name/URL." && exit
-	[ -f "$webdir/blog/$url.html" ] && echo "There is already an existing published entry of that same name/URL." && exit
-	$EDITOR "$webdir/blog/.drafts/$url.html" ;}
+newpost() {
+	read -ep "Give a title for your post: " title
+	if [[ "$title" == *\"* ]]; then
+		FAIL 1 $LINENO 'Double quotation marks (") found in title.'
+	else
+		url() {
+			awk -F '\0' '
+				{
+					gsub(/([:punct:]|^-|-$)/, "", $1)
+					gsub(/(\s|-\+)/, "-", $1)
+					printf("%s\n", tolower($1))
+				}
+			' <<< "$(iconv -cf UTF-8 -t ASCII//TRANSLIT <<< "$title")"
+		}
 
-listandReturn() { printf "Listing contents of %s.\\n" "$1"
+		local HTAccess="$webdir/blog/.htaccess"
+		if [ -f "$HTAccess" ] && [ -r "$HTAccess" ]; then
+			printf "AddDescription \"%s\" \"%s.html\"\n" "$title" "$(url)" >> "$HTAccess"
+		else
+			FAIL 1 $LINENO "File '.htaccess' missing or unreadable."
+		fi
+
+		if [ -f "$webdir/blog/.drafts/$url.html" ]; then
+			FAIL 1 $LINENO "Pre-existing draft entry of the same name/URL."
+		elif [ -f "$webdir/blog/$url.html" ]; then
+			FAIL 1 $LINENO "Pre-existing published entry of the same name/URL."
+		fi
+
+		$EDITOR "$webdir/blog/.drafts/$url.html"
+
+		unset -f url
+	fi
+
+	unset title
+}
+
+listandReturn() {
+	printf "Listing contents of %s.\n" "$1"
 	ls -rc "$1" | awk -F '/' '{print $NF}' | nl
 	read -erp "Pick an entry by number to $2, or press ctrl-c to cancel. " number
 	chosen="$(ls -rc "$1" | nl | grep -w  "$number" | awk '{print $2}')"
-	basefile="$(basename "$chosen")" && base="${basefile%.*}" ;}
+	basefile="$(basename "$chosen")" && base="${basefile%.*}"
+}
 
 publish() { \
 	delete
