Convert spaces to tabs

diff --git a/lb b/lb
--- a/lb
+++ b/lb
@@ -23,19 +23,19 @@ getHelp() { \
 	echo -e "Blog posts will be stored in 'blog/' and drafts will be in 'blog/.drafts/'. To delete drafts, you only need delete their .html files directly, but use the 'lb delete' command to remove finalized posts since they appear in three places."
 }
 
-listandReturn() { 
+listandReturn() {
 	if [[ -z $chosen ]]; then
 		echo "Listing contents of $1."
 		ls -rc $1 | awk -F '/' '{print $NF}' | nl
 		read -rp "Pick an entry by number to $2, or press ctrl-c to cancel. " number
 		chosen=$(ls -rc $1 | nl | grep -w  "$number" | awk '{print $2}')
-	else 
+	else
 		chosen=$(ls -rc $1 | grep $chosen.html ) || \
-	   	echo "Error: File not found" && exit 1	
+		echo "Error: File not found" && exit 1
 	fi
 }
 
-getTitle() { 
+getTitle() {
 	if [[ -z $title ]]; then
 		echo "Post will be stored as draft in $draftdir until finalized."
 		read -rp "Give a title for your post: " title
@@ -45,7 +45,7 @@ getTitle() {
 
 	[ -z $url ] && echo "Error: Empty title!" && exit 1;
 
-	grep "id='$url'" "$blogfile" &>/dev/null && lbdupnum=1 && 
+	grep "id='$url'" "$blogfile" &>/dev/null && lbdupnum=1 &&
 	while [ grep "$url" "$blogfile" ]; do lbdupnum=$((lbdupnum+1)); done
 	[ ! -z ${lbdupnum+x} ] && url="$url"-"$lbdupnum"
 	return 0
@@ -95,7 +95,7 @@ discard() { \
 	}
 
 #optional argument when running this script
-[ -n "$2" ] && title="$2"; chosen="$2" 
+[ -n "$2" ] && title="$2"; chosen="$2"
 
 case "$1" in
 	new) getTitle && postNew ;;
